server:
  port: 8081

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/auth_db
    username: postgres
    password: Tino1372

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
